// Unified application icon set.
//
// This file is GENERATED by `scripts/gen_icons.py`. Do not edit by hand.
// Every variant maps to a standalone, compile-time-embedded SVG (include_str!)
// under assets/icons/. The whole set is normalized to a 24x24 grid,
// stroke=currentColor, fill=none, stroke-width=2 -- so it themes via the
// element's text_color and scales crisply at any DPI.
//
// To add an icon: drop the SVG under assets/icons/ and re-run the script.
// The variant, asset path, from_str key and all() entry are generated
// together from a single data sequence -- no manual wiring required.

macro_rules! declare_icons {
    ($( $variant:ident => ($kebab:literal, $path:literal, $svg_path:literal) ),* $(,)?) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum AppIcon {
            $($variant,)*
        }

        impl AppIcon {
            /// Backward compatibility aliases for Directory -> Folder rename.
            #[allow(non_upper_case_globals)]
            pub const NewDir: AppIcon = AppIcon::NewFolder;
            #[allow(non_upper_case_globals)]
            pub const ExpandDir: AppIcon = AppIcon::ExpandFolder;
            #[allow(non_upper_case_globals)]
            pub const CollapseDir: AppIcon = AppIcon::CollapseFolder;

            /// Asset path of the SVG icon (served by the embedded asset source).
            pub fn path(&self) -> &'static str {
                match self {
                    $( Self::$variant => $path, )*
                }
            }

            /// SVG string content, embedded at compile time via `include_str!`.
            pub fn svg_source(&self) -> &'static str {
                match self {
                    $( Self::$variant => include_str!($svg_path), )*
                }
            }

            /// Look an icon up by its kebab-case asset name (e.g. `"chevron-right"`).
            pub fn from_str(name: &str) -> Option<AppIcon> {
                match name {
                    "new-folder" => Some(Self::NewFolder),
                    "expand-folder" => Some(Self::ExpandFolder),
                    "collapse-folder" => Some(Self::CollapseFolder),
                    $( $kebab => Some(Self::$variant), )*
                    _ => None,
                }
            }

            /// Returns the canonical short name (e.g. `"monitor"`), the inverse of
            /// [`from_str`]. Useful for serializing a project's selected icon.
            pub fn name(self) -> &'static str {
                let p = self.path();
                // All `path()` values are of the form "icons/<name>.svg".
                &p["icons/".len()..p.len() - ".svg".len()]
            }

            /// All icon variants, for exhaustive iteration.
            pub fn all() -> &'static [AppIcon] {
                &[ $( Self::$variant, )* ]
            }
        }
    };
}

declare_icons! {
    Activity => ("activity", "icons/activity.svg", "../../../../assets/icons/activity.svg"),
    AiAssistant => ("ai-assistant", "icons/ai-assistant.svg", "../../../../assets/icons/ai-assistant.svg"),
    ArrowUp => ("arrow-up", "icons/arrow-up.svg", "../../../../assets/icons/arrow-up.svg"),
    Attach => ("panel-attach", "icons/panel-attach.svg", "../../../../assets/icons/panel-attach.svg"),
    Ban => ("ban", "icons/ban.svg", "../../../../assets/icons/ban.svg"),
    Bookmark => ("bookmark", "icons/bookmark.svg", "../../../../assets/icons/bookmark.svg"),
    BrushCleaning => ("brush-cleaning", "icons/brush-cleaning.svg", "../../../../assets/icons/brush-cleaning.svg"),
    Check => ("check", "icons/check.svg", "../../../../assets/icons/check.svg"),
    ChevronDown => ("chevron-down", "icons/chevron-down.svg", "../../../../assets/icons/chevron-down.svg"),
    ChevronLeft => ("chevron-left", "icons/chevron-left.svg", "../../../../assets/icons/chevron-left.svg"),
    ChevronRight => ("chevron-right", "icons/chevron-right.svg", "../../../../assets/icons/chevron-right.svg"),
    ChevronUp => ("chevron-up", "icons/chevron-up.svg", "../../../../assets/icons/chevron-up.svg"),
    ClipboardPaste => ("clipboard-paste", "icons/clipboard-paste.svg", "../../../../assets/icons/clipboard-paste.svg"),
    Close => ("close", "icons/close.svg", "../../../../assets/icons/close.svg"),
    Cloud => ("cloud", "icons/cloud.svg", "../../../../assets/icons/cloud.svg"),
    CloudUpload => ("cloud-upload", "icons/cloud-upload.svg", "../../../../assets/icons/cloud-upload.svg"),
    Code => ("code", "icons/code.svg", "../../../../assets/icons/code.svg"),
    CollapseFolder => ("collapse-dir", "icons/collapse-dir.svg", "../../../../assets/icons/collapse-dir.svg"),
    CommandAction => ("command-action", "icons/command-action.svg", "../../../../assets/icons/command-action.svg"),
    Copy => ("copy", "icons/copy.svg", "../../../../assets/icons/copy.svg"),
    Cpu => ("cpu", "icons/cpu.svg", "../../../../assets/icons/cpu.svg"),
    Database => ("database", "icons/database.svg", "../../../../assets/icons/database.svg"),
    Detach => ("panel-detach", "icons/panel-detach.svg", "../../../../assets/icons/panel-detach.svg"),
    Download => ("download", "icons/download.svg", "../../../../assets/icons/download.svg"),
    Duplicate => ("duplicate", "icons/duplicate.svg", "../../../../assets/icons/duplicate.svg"),
    Edit => ("edit", "icons/edit.svg", "../../../../assets/icons/edit.svg"),
    Eraser => ("eraser", "icons/eraser.svg", "../../../../assets/icons/eraser.svg"),
    ExpandFolder => ("expand-dir", "icons/expand-dir.svg", "../../../../assets/icons/expand-dir.svg"),
    ExternalLink => ("external-link", "icons/external-link.svg", "../../../../assets/icons/external-link.svg"),
    Eye => ("eye", "icons/eye.svg", "../../../../assets/icons/eye.svg"),
    EyeOff => ("eye-off", "icons/eye-off.svg", "../../../../assets/icons/eye-off.svg"),
    Favorite => ("favorite", "icons/favorite.svg", "../../../../assets/icons/favorite.svg"),
    File => ("file", "icons/file.svg", "../../../../assets/icons/file.svg"),
    FileFilled => ("file-filled", "icons/file-filled.svg", "../../../../assets/icons/file-filled.svg"),
    Focus => ("focus", "icons/focus.svg", "../../../../assets/icons/focus.svg"),
    Folder => ("folder", "icons/folder.svg", "../../../../assets/icons/folder.svg"),
    FolderInput => ("folder-input", "icons/folder-input.svg", "../../../../assets/icons/folder-input.svg"),
    FolderOpen => ("folder_open", "icons/folder_open.svg", "../../../../assets/icons/folder_open.svg"),
    FolderOutput => ("folder-output", "icons/folder-output.svg", "../../../../assets/icons/folder-output.svg"),
    Fullscreen => ("fullscreen", "icons/fullscreen.svg", "../../../../assets/icons/fullscreen.svg"),
    FullscreenExit => ("fullscreen-exit", "icons/fullscreen-exit.svg", "../../../../assets/icons/fullscreen-exit.svg"),
    GitBranch => ("git-branch", "icons/git-branch.svg", "../../../../assets/icons/git-branch.svg"),
    Globe => ("globe", "icons/globe.svg", "../../../../assets/icons/globe.svg"),
    HardDrive => ("hard-drive", "icons/hard-drive.svg", "../../../../assets/icons/hard-drive.svg"),
    Help => ("help", "icons/help.svg", "../../../../assets/icons/help.svg"),
    History => ("history", "icons/history.svg", "../../../../assets/icons/history.svg"),
    Image => ("image", "icons/image.svg", "../../../../assets/icons/image.svg"),
    Info => ("info", "icons/info.svg", "../../../../assets/icons/info.svg"),
    Keyboard => ("keyboard", "icons/keyboard.svg", "../../../../assets/icons/keyboard.svg"),
    Layers2 => ("layers-2", "icons/layers-2.svg", "../../../../assets/icons/layers-2.svg"),
    Layout => ("layout", "icons/layout.svg", "../../../../assets/icons/layout.svg"),
    Link => ("link", "icons/link.svg", "../../../../assets/icons/link.svg"),
    LoaderCircle => ("loader-circle", "icons/loader-circle.svg", "../../../../assets/icons/loader-circle.svg"),
    Lock => ("lock", "icons/lock.svg", "../../../../assets/icons/lock.svg"),
    Memory => ("memory", "icons/memory.svg", "../../../../assets/icons/memory.svg"),
    Minimize => ("minimize", "icons/minimize.svg", "../../../../assets/icons/minimize.svg"),
    Monitor => ("monitor", "icons/monitor.svg", "../../../../assets/icons/monitor.svg"),
    MonitorClock => ("monitor-clock", "icons/monitor-clock.svg", "../../../../assets/icons/monitor-clock.svg"),
    MonitorUsers => ("monitor-users", "icons/monitor-users.svg", "../../../../assets/icons/monitor-users.svg"),
    MoreMenu => ("more_menu", "icons/more_menu.svg", "../../../../assets/icons/more_menu.svg"),
    Network => ("network", "icons/network.svg", "../../../../assets/icons/network.svg"),
    NewFile => ("new-file", "icons/new-file.svg", "../../../../assets/icons/new-file.svg"),
    NewFolder => ("new-dir", "icons/new-dir.svg", "../../../../assets/icons/new-dir.svg"),
    PaintRoller => ("paint-roller", "icons/paint-roller.svg", "../../../../assets/icons/paint-roller.svg"),
    Pause => ("pause", "icons/pause.svg", "../../../../assets/icons/pause.svg"),
    Play => ("play", "icons/play.svg", "../../../../assets/icons/play.svg"),
    Plus => ("plus", "icons/plus.svg", "../../../../assets/icons/plus.svg"),
    QuickCommand => ("quick-command", "icons/quick-command.svg", "../../../../assets/icons/quick-command.svg"),
    Refresh => ("refresh", "icons/refresh.svg", "../../../../assets/icons/refresh.svg"),
    Save => ("save", "icons/save.svg", "../../../../assets/icons/save.svg"),
    Search => ("search", "icons/search.svg", "../../../../assets/icons/search.svg"),
    SelectAll => ("select-all", "icons/select-all.svg", "../../../../assets/icons/select-all.svg"),
    Send => ("send", "icons/send.svg", "../../../../assets/icons/send.svg"),
    Serial => ("serial", "icons/serial.svg", "../../../../assets/icons/serial.svg"),
    Server => ("server", "icons/server.svg", "../../../../assets/icons/server.svg"),
    Settings => ("settings", "icons/settings.svg", "../../../../assets/icons/settings.svg"),
    Share => ("share", "icons/share.svg", "../../../../assets/icons/share.svg"),
    Shield => ("shield", "icons/shield.svg", "../../../../assets/icons/shield.svg"),
    SidebarLeft => ("sidebar-left", "icons/sidebar-left.svg", "../../../../assets/icons/sidebar-left.svg"),
    SidebarRight => ("sidebar-right", "icons/sidebar-right.svg", "../../../../assets/icons/sidebar-right.svg"),
    SortAsc => ("sort-asc", "icons/sort-asc.svg", "../../../../assets/icons/sort-asc.svg"),
    SortDesc => ("sort-desc", "icons/sort-desc.svg", "../../../../assets/icons/sort-desc.svg"),
    SplitHorizontal => ("split-horizontal", "icons/split-horizontal.svg", "../../../../assets/icons/split-horizontal.svg"),
    SplitVertical => ("split-vertical", "icons/split-vertical.svg", "../../../../assets/icons/split-vertical.svg"),
    SquareActivity => ("square-activity", "icons/square-activity.svg", "../../../../assets/icons/square-activity.svg"),
    Stop => ("stop", "icons/stop.svg", "../../../../assets/icons/stop.svg"),
    Telnet => ("telnet", "icons/telnet.svg", "../../../../assets/icons/telnet.svg"),
    Terminal => ("terminal", "icons/terminal.svg", "../../../../assets/icons/terminal.svg"),
    TerminalMinimized => ("terminal-minimized", "icons/terminal-minimized.svg", "../../../../assets/icons/terminal-minimized.svg"),
    Transfer => ("transfer", "icons/transfer.svg", "../../../../assets/icons/transfer.svg"),
    Trash => ("trash", "icons/trash.svg", "../../../../assets/icons/trash.svg"),
    Tunnel => ("tunnel", "icons/tunnel.svg", "../../../../assets/icons/tunnel.svg"),
    TunnelD => ("tunnel-d", "icons/tunnel-d.svg", "../../../../assets/icons/tunnel-d.svg"),
    TunnelL => ("tunnel-l", "icons/tunnel-l.svg", "../../../../assets/icons/tunnel-l.svg"),
    TunnelR => ("tunnel-r", "icons/tunnel-r.svg", "../../../../assets/icons/tunnel-r.svg"),
    Unlink => ("unlink", "icons/unlink.svg", "../../../../assets/icons/unlink.svg"),
    Upload => ("upload", "icons/upload.svg", "../../../../assets/icons/upload.svg"),
    WindowCloseBreeze => ("window-close-breeze", "icons/window-close-breeze.svg", "../../../../assets/icons/window-close-breeze.svg"),
    WindowCloseCsd => ("window-close-csd", "icons/window-close-csd.svg", "../../../../assets/icons/window-close-csd.svg"),
    WindowCloseWin11 => ("window-close-win11", "icons/window-close-win11.svg", "../../../../assets/icons/window-close-win11.svg"),
    WindowMaximizeBreeze => ("window-maximize-breeze", "icons/window-maximize-breeze.svg", "../../../../assets/icons/window-maximize-breeze.svg"),
    WindowMaximizeCsd => ("window-maximize-csd", "icons/window-maximize-csd.svg", "../../../../assets/icons/window-maximize-csd.svg"),
    WindowMaximizeWin11 => ("window-maximize-win11", "icons/window-maximize-win11.svg", "../../../../assets/icons/window-maximize-win11.svg"),
    WindowMinimizeBreeze => ("window-minimize-breeze", "icons/window-minimize-breeze.svg", "../../../../assets/icons/window-minimize-breeze.svg"),
    WindowMinimizeCsd => ("window-minimize-csd", "icons/window-minimize-csd.svg", "../../../../assets/icons/window-minimize-csd.svg"),
    WindowMinimizeWin11 => ("window-minimize-win11", "icons/window-minimize-win11.svg", "../../../../assets/icons/window-minimize-win11.svg"),
    WindowRestoreBreeze => ("window-restore-breeze", "icons/window-restore-breeze.svg", "../../../../assets/icons/window-restore-breeze.svg"),
    WindowRestoreCsd => ("window-restore-csd", "icons/window-restore-csd.svg", "../../../../assets/icons/window-restore-csd.svg"),
    WindowRestoreWin11 => ("window-restore-win11", "icons/window-restore-win11.svg", "../../../../assets/icons/window-restore-win11.svg"),
    Wrapline => ("wrapline", "icons/wrapline.svg", "../../../../assets/icons/wrapline.svg"),
}

#[cfg(test)]
mod tests {
    use super::AppIcon;

    #[test]
    fn name_is_inverse_of_from_str() {
        for &icon in AppIcon::all() {
            let name = icon.name();
            assert_eq!(AppIcon::from_str(name), Some(icon), "round-trip failed for {name}");
        }
    }
}
