#!/usr/bin/env python3
"""Generate ``crates/velowork-ui/src/icon/icon_gen.rs`` from the SVG assets.

Single source of truth: ``assets/icons/*.svg``.  Each file becomes one
``AppIcon`` variant.  The generated file uses a ``declare_icons!`` declarative
macro so that ``path()``, ``svg_source()``, ``from_str()``, ``name()`` and ``all()``
are all derived from a *single* data sequence -- there is no way to add a
variant without also wiring up its asset path, and no way to mistype a string
literal.

Run::

    python3 scripts/gen_icons.py
"""

from __future__ import annotations

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_DIR = os.path.join(ROOT, "assets", "icons")
OUT_FILE = os.path.join(ROOT, "crates", "velowork-ui", "src", "icon", "icon_gen.rs")

# Path (relative to icon_gen.rs) used by include_str! to embed each SVG.
INCLUDE_PREFIX = "../../../../assets/icons/"

# Filename stem -> explicit enum variant name.  Only needed when the default
# PascalCase conversion is not the desired identifier.
OVERRIDES: dict[str, str] = {
    "panel-detach": "Detach",   # file is panel-detach.svg but the variant is `Detach`
    "panel-attach": "Attach",   # file is panel-attach.svg but the variant is `Attach`
    "new-dir": "NewFolder",
    "expand-dir": "ExpandFolder",
    "collapse-dir": "CollapseFolder",
}

# SVG files that exist in assets/ but are NOT part of the AppIcon set
# (orphaned / duplicate assets).  Keep this list intentional and documented.
EXCLUDES: set[str] = set()


def to_pascal(stem: str) -> str:
    """Convert a kebab/snake filename stem to a PascalCase identifier."""
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[-_]", stem) if p)


def collect() -> list[tuple[str, str, str, str]]:
    entries: list[tuple[str, str, str, str]] = []
    for fn in sorted(os.listdir(ICONS_DIR)):
        if not fn.endswith(".svg"):
            continue
        stem = fn[: -len(".svg")]
        if stem in EXCLUDES:
            continue
        variant = OVERRIDES.get(stem, to_pascal(stem))
        kebab = stem
        path = f"icons/{stem}.svg"
        svg_path = f"{INCLUDE_PREFIX}{stem}.svg"
        entries.append((variant, kebab, path, svg_path))
    # Deterministic output: sort by variant identifier.
    entries.sort(key=lambda e: e[0])
    return entries


HEADER = '''// Unified application icon set.
//
// This file is GENERATED by `scripts/gen_icons.py`. Do not edit by hand.
// Every variant maps to a standalone, compile-time-embedded SVG (include_str!)
// under assets/icons/. The whole set is normalized to a 24x24 grid,
// stroke=currentColor, fill=none, stroke-width=2 -- so it themes via the
// element's text_color and scales crisply at any DPI.
//
// To add an icon: drop the SVG under assets/icons/ and re-run the script.
// The variant, asset path, from_str key and all() entry are generated
// together from a single data sequence -- no manual wiring required.

macro_rules! declare_icons {
    ($( $variant:ident => ($kebab:literal, $path:literal, $svg_path:literal) ),* $(,)?) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum AppIcon {
            $($variant,)*
        }

        impl AppIcon {
            /// Backward compatibility aliases for Directory -> Folder rename.
            #[allow(non_upper_case_globals)]
            pub const NewDir: AppIcon = AppIcon::NewFolder;
            #[allow(non_upper_case_globals)]
            pub const ExpandDir: AppIcon = AppIcon::ExpandFolder;
            #[allow(non_upper_case_globals)]
            pub const CollapseDir: AppIcon = AppIcon::CollapseFolder;

            /// Asset path of the SVG icon (served by the embedded asset source).
            pub fn path(&self) -> &'static str {
                match self {
                    $( Self::$variant => $path, )*
                }
            }

            /// SVG string content, embedded at compile time via `include_str!`.
            pub fn svg_source(&self) -> &'static str {
                match self {
                    $( Self::$variant => include_str!($svg_path), )*
                }
            }

            /// Look an icon up by its kebab-case asset name (e.g. `"chevron-right"`).
            pub fn from_str(name: &str) -> Option<AppIcon> {
                match name {
                    "new-folder" => Some(Self::NewFolder),
                    "expand-folder" => Some(Self::ExpandFolder),
                    "collapse-folder" => Some(Self::CollapseFolder),
                    $( $kebab => Some(Self::$variant), )*
                    _ => None,
                }
            }

            /// Returns the canonical short name (e.g. `"monitor"`), the inverse of
            /// [`from_str`]. Useful for serializing a project's selected icon.
            pub fn name(self) -> &'static str {
                let p = self.path();
                // All `path()` values are of the form "icons/<name>.svg".
                &p["icons/".len()..p.len() - ".svg".len()]
            }

            /// All icon variants, for exhaustive iteration.
            pub fn all() -> &'static [AppIcon] {
                &[ $( Self::$variant, )* ]
            }
        }
    };
}

declare_icons! {
'''

FOOTER = '''}

#[cfg(test)]
mod tests {
    use super::AppIcon;

    #[test]
    fn name_is_inverse_of_from_str() {
        for &icon in AppIcon::all() {
            let name = icon.name();
            assert_eq!(AppIcon::from_str(name), Some(icon), "round-trip failed for {name}");
        }
    }
}
'''


def main() -> None:
    entries = collect()
    out: list[str] = [HEADER]
    for variant, kebab, path, svg_path in entries:
        out.append(f'    {variant} => ("{kebab}", "{path}", "{svg_path}"),\n')
    out.append(FOOTER)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.writelines(out)
    print(f"Wrote {len(entries)} icons to {os.path.relpath(OUT_FILE, ROOT)}")


if __name__ == "__main__":
    main()
